server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qq?serverTimezone=GMT%2b8
    username: root
    password: 5252
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsps/
  redis:
    host: 192.168.83.234
    database: 0
    port: 6379
    password: 123456
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
  style: camelhump
mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件
configuration:
  mapUnderscoreToCamelCase: true
  type-aliases-package: com.stock.entity
